# Site Settings
#=include site.yml

# Social Media Settings
# Remove the item if you don't need it
#=include social.yml

# Posts Settings
#=include posts.yml

# Advanced Settings
#=include advanced.yml

# Pagination Settings
paginate_path: "/page/:num/"
pagination:
  per_page: 6
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Build settings
# paginate: 5
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
categories_folder: category

# SASS
sass:
  style: compressed

  
# Plugins
plugins:
  - jekyll-paginate-v2
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]
